apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment # Deployment name
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.13.5-alpine
          ports:
            - containerPort: 80
              hostPort: 80
