apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec: # DeploymentSpec
  template: # PodTemplateSpec
    metadata:
      labels:
        app: nginx
    spec: # PodSpec
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
      containers:
        - name: nginx
          image: nginx:1.13.6-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-configmap
              mountPath: /html/index.html
              subPath: index.html
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
