apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
      <head>
        <style>
          body {
              width: 35em;
              margin: 0 auto;
              font-family: Tahoma, Verdana, Arial, sans-serif;
          }
        </style>
      </head>
      <body>
        <h1>Welcome to the City of Gold!</h1>
        <p>Freedom and justice for all!</p>
        <p>I just got updated!</p>
        <address>(c) 2017 Ilya Sotkov</address>
      </body>
    </html>
