apiVersion: v1beta1
kind: CronJob
metadata:
  name: example_cronjob
spec: # CronJobSpec
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 2
  schedule:
  startingDeadlineSeconds: 5
  successfulJobsHistoryLimit: 4
  suspend: true
  jobTemplate:
    spec: # JobSpec
      template:
        spec:
          containers:
            image: certbot/certbot:latest
