apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec: # ServiceSpec
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /freedom
            backend:
              serviceName: nginx-service
              servicePort: 80
