apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    app: {{ template "nginx-release.name" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: nginx-service
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ template "nginx-release.name" . }}
spec: # ServiceSpec
  ports:
    - port: 80
      name: http-something
  selector:
    app: {{ template "nginx-release.name" . }}
