apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec: # DeploymentSpec
  selector:
    matchLabels:
      app: nginx

  # DeploymentSpec defaults
  paused: false
  minReadySeconds: 0
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template: # PodTemplateSpec
    metadata:
      labels:
        app: nginx
    spec: # PodSpec
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
        - name: html-configmap
          configMap:
            name: html-configmap
      containers:
        - name: nginx
          image: nginx:1.13.6-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-configmap
              mountPath: /etc/nginx
            - name: html-configmap
              mountPath: /html
