# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# nameOverride: rails
image:
  repository: ilyasotkov/hello-react-rails
  tag: latest
  pullPolicy: IfNotPresent

serviceType: ClusterIP
servicePort: 3000

ingress:
  # If true, an Ingress Resource will be created
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  hosts:
    - rails.c6ns.pw
  tls:
    - secretName: rails-c6ns-pw-tls
      hosts:
        - rails.c6ns.pw

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Configuration values for the postgresql dependency.
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
##
postgresql:
  persistence:
    enabled: true
  postgresUser: postgres
  postgresPassword: postgres
