apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: productpage-deafult
spec:
  destination:
    name: productpage
  precedence: 1
  route:
    - labels:
        version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default
spec:
  destination:
    name: ratings
  precedence: 1
  route:
    - labels:
        version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: details-default
spec:
  destination:
    name: details
  precedence: 1
  route:
    - labels:
        version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-test-v2
spec:
  destination:
    name: reviews
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=jason)(;.*)?$"
  route:
    - labels:
        version: v2
